- name: disabling old  version and enabling nodejs
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: installing npm
  ansible.builtin.command: npm install
  args:
    chdir: /app
