- name: adding user
  ansible.builtin.user:
    name: roboshop

- name: removing the directory if present and creating
  ansible.builtin.file:
    path: /app
    state: absent
  
- name: creating directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download {{component}} application
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /tmp

- name: unzipping the file
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes