- name: installing golang
  ansible.builtin.package:
    name: golang
    state: present

- name: changing directory
  ansible.builtin.command: go mod init dispatch; go get; go build
  args:
    chdir: /app