- name: install maven
  ansible.builtin.package:
    name: maven
    state: present

- name: downloading the dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: renaming the file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app