- name: install mysql
  ansible.builtin.package:
    name: mysql
    state: present

- name: check cities schema exists or not
  ansible.builtin.command:  mysql -h  -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: schema

- name: print output
  ansible.builtin.debug:
    msg: "schema output: {{schema}}"

- name: load cities data
  ansible.builtin.shell: "mysql -h mysql.pjdevops.online -uroot -p{{mysql_password}}  < /app/schema/shipping.sql"
  when: schema.stdout != "1"

- name: restarting shipping
  ansible.builtin.service:
    name: shipping
    state: restarted