# - name: copy {{component}} services
#   ansible.builtin.copy:
#     src: "{{component}}.service" 
#     dest: "/etc/systemd/system/{{component}}.service"

- name: "copy {{component}} services"
  ansible.builtin.templet:
    src: "{{component}}.service.j2" 
    dest: "/etc/systemd/system/{{component}}.service"

- name: deamon realod and start
  ansible.builtin.service:
    daemon-reload: true

- name: start and enable {{component}}
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    enabled: yes